import { Category } from "../admin/category.type";

export const demoCategories: Category[] = [
  // ── Level 0 (Root) ──────────────────────────────────────────
  {
    _id: "l0-1",
    name: "Men Fashion",
    slug: "men-fashion",
    parentId: null,
    level: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l0-2",
    name: "Women Fashion",
    slug: "women-fashion",
    parentId: null,
    level: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l0-3",
    name: "Home & Living",
    slug: "home-living",
    parentId: null,
    level: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l0-4",
    name: "Kids & Toys",
    slug: "kids-toys",
    parentId: null,
    level: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l0-5",
    name: "Personal Care & Wellness",
    slug: "personal-care",
    parentId: null,
    level: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l0-6",
    name: "Mobiles & Tablets",
    slug: "mobiles-tablets",
    parentId: null,
    level: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l0-7",
    name: "Consumer Electronics",
    slug: "consumer-electronics",
    parentId: null,
    level: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Level 1 → Men Fashion ───────────────────────────────────
  {
    _id: "l1-1",
    name: "Mens Clothing",
    slug: "mens-clothing",
    parentId: "l0-1",
    level: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l1-2",
    name: "Footwear",
    slug: "footwear",
    parentId: "l0-1",
    level: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l1-3",
    name: "Accessories",
    slug: "accessories",
    parentId: "l0-1",
    level: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Level 1 → Women Fashion ─────────────────────────────────
  {
    _id: "l1-4",
    name: "Womens Clothing",
    slug: "womens-clothing",
    parentId: "l0-2",
    level: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l1-5",
    name: "Women Footwear",
    slug: "women-footwear",
    parentId: "l0-2",
    level: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l1-6",
    name: "Handbags",
    slug: "handbags",
    parentId: "l0-2",
    level: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Level 1 → Home & Living ─────────────────────────────────
  {
    _id: "l1-7",
    name: "Furniture",
    slug: "furniture",
    parentId: "l0-3",
    level: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l1-8",
    name: "Kitchen & Dining",
    slug: "kitchen-dining",
    parentId: "l0-3",
    level: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Level 2 → Mens Clothing ─────────────────────────────────
  {
    _id: "l2-1",
    name: "Men Top Wear",
    slug: "men-top-wear",
    parentId: "l1-1",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l2-2",
    name: "Men Sports Wear",
    slug: "men-sports-wear",
    parentId: "l1-1",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l2-3",
    name: "Men Ethnic Wear",
    slug: "men-ethnic-wear",
    parentId: "l1-1",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l2-4",
    name: "Men Bottom Wear",
    slug: "men-bottom-wear",
    parentId: "l1-1",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l2-5",
    name: "Top & Bottom Set",
    slug: "top-bottom-set",
    parentId: "l1-1",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l2-6",
    name: "Men Inner & Sleepwear",
    slug: "men-inner-sleepwear",
    parentId: "l1-1",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Level 2 → Footwear ──────────────────────────────────────
  {
    _id: "l2-7",
    name: "Casual Shoes",
    slug: "casual-shoes",
    parentId: "l1-2",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l2-8",
    name: "Sports Shoes",
    slug: "sports-shoes",
    parentId: "l1-2",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l2-9",
    name: "Formal Shoes",
    slug: "formal-shoes",
    parentId: "l1-2",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l2-10",
    name: "Sandals",
    slug: "sandals",
    parentId: "l1-2",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Level 2 → Womens Clothing ───────────────────────────────
  {
    _id: "l2-11",
    name: "Tops & Tees",
    slug: "tops-tees",
    parentId: "l1-4",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l2-12",
    name: "Dresses",
    slug: "dresses",
    parentId: "l1-4",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l2-13",
    name: "Sarees",
    slug: "sarees",
    parentId: "l1-4",
    level: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Level 3 → Men Top Wear ──────────────────────────────────
  {
    _id: "l3-1",
    name: "T-Shirts",
    slug: "t-shirts",
    parentId: "l2-1",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l3-2",
    name: "Shirts",
    slug: "shirts",
    parentId: "l2-1",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l3-3",
    name: "Top & Bottom Set",
    slug: "top-bottom-set-l3",
    parentId: "l2-1",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l3-4",
    name: "Personalized Tshirts",
    slug: "personalized-tshirts",
    parentId: "l2-1",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l3-5",
    name: "Dad & Daughter Tshirts",
    slug: "dad-daughter-tshirts",
    parentId: "l2-1",
    level: 3,
    isActive: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l3-6",
    name: "Dad & Son Tshirts",
    slug: "dad-son-tshirts",
    parentId: "l2-1",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l3-7",
    name: "Active Tshirts",
    slug: "active-tshirts",
    parentId: "l2-1",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Level 3 → Casual Shoes ──────────────────────────────────
  {
    _id: "l3-8",
    name: "Loafers",
    slug: "loafers",
    parentId: "l2-7",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l3-9",
    name: "Sneakers",
    slug: "sneakers",
    parentId: "l2-7",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l3-10",
    name: "Canvas Shoes",
    slug: "canvas-shoes",
    parentId: "l2-7",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Level 3 → Dresses ───────────────────────────────────────
  {
    _id: "l3-11",
    name: "Maxi Dresses",
    slug: "maxi-dresses",
    parentId: "l2-12",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l3-12",
    name: "Mini Dresses",
    slug: "mini-dresses",
    parentId: "l2-12",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "l3-13",
    name: "Party Dresses",
    slug: "party-dresses",
    parentId: "l2-12",
    level: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
